version: "3.8"

services:
  backend:
    build:
      context: .
      target: build-backend
    container_name: backend
    ports:
      - "3000:3000"
    command: bash -c "cd /app/backend && bundle exec rails server -b 0.0.0.0"
    volumes:
      - ./project/backend:/app/backend
    depends_on:
      - db

  frontend:
    build:
      context: .
      target: build-frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

